version: "3"

services:
  wg:
    build: .
    image: wg-ui:latest
    container_name: wgui
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - SESSION_SECRET=vnsjdvb9134f39hvn9249
      - WGUI_USERNAME=alpha
      - WGUI_PASSWORD=Negjqgfhjkm1!
      - WGUI_MANAGE_START=false
      - WGUI_MANAGE_RESTART=false
      - WGUI_API_KEY=test
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - /etc/wireguard:/etc/wireguard
